name: Deploy our first pipeline for test-server
on:
 push:
  branches: 
     - master
jobs:
 web-deploy:
   name: deploy-test
   runs-on: ubuntu-latest
   steps:
     - name: clone our code
       uses: actions/checkout@v2

     - name: 📂 Sync files
       uses: SamKirkland/FTP-Deploy-Action@4.3.2
       with:
        server: mega-express.info
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
